language: c

compiler: clang # only for trevis

before_script:
  - sudo apt update
  - sudo apt install libtesseract-dev tesseract-ocr libleptonica-dev make llvm-7-dev clang-7

script:
  - ./configure
  - make
